version: "3"

services:
  snowplow-mini:
    image: mrosack/snowplow-mini-upgraded
    ports:
    - 80:80
    - 8080:8080
    - 9200:9200
    - 5601:5601
    - 8081:8081
    volumes:
    - ./iglu-volume:/var/lib/postgresql/9.6/main/base
    - ./elastic-volume:/var/lib/elasticsearch
