version: "3"

services:

  iglu:
    build: iglu/
    ports:
      - 8080:8080
    networks:
      - telemetry

  elasticsearch:
    build: elasticsearch/
    ports:
      - 9200:9200
      - 9300:9300
    #volumes:
      #- ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - telemetry

  kibana:
    build: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    ports:
      - "5601:5601"
    networks:
      - telemetry
    depends_on:
      - elasticsearch

  logstash:
    build: logstash/
    ports:
      - 9600:9600
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - telemetry
    depends_on:
      - elasticsearch

  snowplow:
    build: snowplow/
    ports:
      - 14654:14654
    networks:
      - telemetry
    depends_on:
      - iglu
      - elasticsearch

networks:

  telemetry:
    driver: bridge
