version: "3"

services:
  snowplow-mini:
    build: ./snowplow-docker
    ports:
      - 80:80
      - 8080:8080
      - 5601:5601
      - 8081:8081
      - 9200:9200
    volumes:
      - ./snowplow-docker/elasticsearch:/var/lib/elasticsearch
      #- ./snowplow-docker/postgresql:/var/lib/postgresql
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - telemetry

  logstash:
    build: ./logstash-docker
    ports:
      - 9600:9600
    volumes:
      - ./logstash-docker/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash-docker/pipeline:/usr/share/logstash/pipeline
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - snowplow-mini
    networks:
      - telemetry

networks:

  telemetry:
    driver: bridge
